### ISSUE TITLE
Firebase TODO's

### ISSUE THREAD

**Issue by mrrobot16** [mrrobot16/irs-copilot-api#1]
- [x] User collection CRUD 
- - [x] C
- - [x] R
- - [x] U
- - [x] D

- [x] User collection CRUD Tests
- - [x] C
- - [x] R
- - [x] U
- - [x] D

- [x] Conversation collection CRUD 
- - [x] C
- - [x] R
- - [x] U
- - [x] D

- [x] Conversation collection CRD Tests
- - [x] C
- - [x] R
- - [x] U
- - [x] D
